### ISSUE TITLE
Spring Boot 应用监控

### ISSUE THREAD

**Issue by x2zh** [x2zh/x2zh.github.io#10]
# 一、创建被监控的Java应用
1、创建 Spring Boot 应用，选择: `web-starter`, `actuator-starter`, `micrometer-registry-prometheus`, `devtools`
```groovy
dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'io.micrometer:micrometer-registry-prometheus'
    compileOnly 'org.projectlombok:lombok'
    developmentOnly 'org.springframework.boot:spring-boot-devtools'
    annotationProcessor 'org.projectlombok:lombok'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}
```
2、开启全部的endpoint的web形式exposing
```yaml
management:
  endpoints:
    web:
      exposure:
        include: "*"
```

3、构建应用
```bash
gradle assemble
```
4、启动应用
```bash
 java -jar build/libs/actuator-learning-0.0.1-SNAPSHOT.jar
```
5、访问应用的actuator路径，查看所有的endpoint [http://localhost:8080/acutator](http://localhost:8080/acutator)

# 二、使用 prometheus 采集应用数据
1、安装prometheus
```bash
sudo apt install prometheus
```
2、查看prometheus的状态
```bash
sudo systemctl status prometheus
```
正常状态应该是`active(running)`
3、查看prometheus的systemd配置文件
```bash
sudo systemctl cat prometheus
```
内容如下，主要关注环境变量文件
```
...
EnvironmentFile=/etc/default/prometheus
ExecStart=/usr/bin/prometheus $ARGS
...
```
4、检查环境变量文件的内容, 可以知道prometheus默认的配置文件路径为`/etc/prometheus/prometheus.yml`
```bash
cat /etc/default/prometheus
```
5、查看配置文件内容，并添加定义拉取上面的java 应用指标的job
```bash
sudo vim /etc/prometheus/prometheus.yml
```
在命令模式下使用`G`跳到最后一行，在`scrape_configs`增加如下配置：
```yaml
- job_name: 'web-server'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    scrape_timeout: 5s
    static_configs:
      - targets: ['192.168.56.17:8080', '192.168.56.18:8080']
```
抓去间隔为5s，target是暴露指标的应用的地址和端口
6、重启prometheus
```bash
sudo systemctl restart prometheus
```
7、访问prometheus: [http://localhost:9090](http://localhost:9090)，输入简单的PromQL(Prometheus Query Language)表达式
```PromQL
rate(http_server_requests_seconds_count[10s])
```
8、在status页面可以检查应用的各项配置和被监控节点的状态
